name: carwash
description: "Carwash"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+11

environment:
  sdk: '>=3.0.0-277.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  uuid: ^4.1.0
  flutter_svg: ^2.0.9
  flutter_launcher_icons: ^0.13.1
  shared_preferences: ^2.2.2
  flutter_lints: ^3.0.2
  flutter_native_splash: ^2.2.19
  package_info_plus: ^7.0.0
  intl: ^0.19.0
  http: ^1.1.2
  web: ^0.5.1
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/icons/

flutter_native_splash:
  color: "#ffeedd"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/carwash.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/carwash.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/carwash.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/carwash.png"